### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by ugintl** [code-rider/coderiders#2]
PHP: 8.1
Drupal: 10.2

TypeError: array_merge(): Argument #2 must be of type array, null given in array_merge() (line 907 of core\includes\install.inc).

**Comment by code-rider** [comment]
Hi
thanks for pointing this out and also for using this repository.
this problem is related to https://www.drupal.org/project/fences module 
issue is already created and merged in dev branch 
https://www.drupal.org/project/fences/issues/3446610
now you have both options use dev branch of this module or user older branch 
I have just tested with 3.0.0

the full installation process is below

composer create-project drupal/recommended-project project-name.com
cd project-name.com 
composer require 'drupal/addtoany:^2.0'
composer require 'drupal/better_exposed_filters:^6.0'
composer require 'drupal/captcha:^2.0'
composer require 'drupal/ctools:^4.0'
composer require 'drupal/entity_reference_revisions:^1.11'
composer require 'drupal/fences:3.0.0'
composer require 'drupal/jquery_ui:^1.6'
composer require 'drupal/jquery_ui_datepicker:^2.0'
composer require 'drupal/jquery_ui_slider:^2.0'
composer require 'drupal/jquery_ui_touch_punch:^1.1'
composer require 'drupal/paragraphs:^1.17'
composer require 'drupal/pathauto:^1.12'
composer require 'drupal/token:^1.14'
composer require 'drupal/twig_tweak:^3.3'
composer require 'drupal/january_theme:^1.0'

download CodeRiders and place in profile folder
webroot/web/profiles/coderiders

you can install drupal with CodeRiders profile

Thanks

**Comment by code-rider** [comment]
Hope this will fix this issue

**Comment by ugintl** [comment]
Installed successfully, but now it says, "Website encountered an unexpected error".

**Comment by ugintl** [comment]
I added `$config['system.logging']['error_level'] = 'verbose';` to settings.php and it showed me following errors

```
Error: Class "Symfony\Cmf\Component\Routing\RouteObjectInterface" not found in january_preprocess_block() (line 176 of themes\contrib\january_theme\january.theme).

call_user_func_array('january_preprocess_block', Array) (Line: 261)
Drupal\Core\Theme\ThemeManager->render('block', Array) (Line: 480)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 493)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 240)
Drupal\Core\Render\Renderer->render(Array) (Line: 475)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 52)
__TwigTemplate_6f82d716071a25ee3f6a328219a9442a->doDisplay(Array, Array) (Line: 394)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 367)
Twig\Template->display(Array) (Line: 379)
Twig\Template->render(Array) (Line: 38)
Twig\TemplateWrapper->render(Array) (Line: 39)
twig_render_template('core/modules/layout_discovery/layouts/onecol/layout--onecol.html.twig', Array) (Line: 348)
Drupal\Core\Theme\ThemeManager->render('layout__onecol', Array) (Line: 480)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 493)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 493)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 240)
Drupal\Core\Render\Renderer->render(Array) (Line: 475)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 136)
__TwigTemplate_a5b180320449003057c9523d671d6e51->doDisplay(Array, Array) (Line: 394)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 367)
Twig\Template->display(Array) (Line: 379)
Twig\Template->render(Array) (Line: 38)
Twig\TemplateWrapper->render(Array) (Line: 39)
twig_render_template('themes/contrib/january_theme/templates/content/node.html.twig', Array) (Line: 348)
Drupal\Core\Theme\ThemeManager->render('node', Array) (Line: 480)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 240)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 238)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 627)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 239)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 128)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'kernel.view') (Line: 186)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 76)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 28)
Drupal\Core\StackMiddleware\ContentLength->handle(Object, 1, 1) (Line: 32)
Drupal\big_pipe\StackMiddleware\ContentLength->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 36)
Drupal\Core\StackMiddleware\AjaxPageState->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object, 1, 1) (Line: 704)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

**Comment by code-rider** [comment]
see this issue 
https://www.drupal.org/project/january_theme/issues/3359653
and this patch is applied to next version 
can you please apply this patch
https://www.drupal.org/files/issues/2023-05-11/3359653-1_0.patch
and also this one mentioned in readme file of this profile
https://www.drupal.org/project/january_theme/issues/3389460

**Comment by ugintl** [comment]
For anyone who faces these issues, please apply this patch https://www.drupal.org/files/issues/2023-09-25/title-solver-3389460_0.patch and this patch https://www.drupal.org/files/issues/2023-05-11/3359653-1_0.patch

After that follow **Step 4** from the Read Me file

The theme is beautiful. Really good work. 🥇
